##############################################################################
#	Makefile.test
#	Zac Hester
#	2012-09-19 - 2014-03-05
##############################################################################

# This file is relative to the unit test directory (not this file's dir).
include ../../build/gcc/Makefile.inc

# Project environment
BLDDIR = build

# Capture the full path to the unit test.
TEST_PATH := $(shell pwd)

# Extract the target unit test module name.
TEST := $(shell basename $(TEST_PATH))

# Source files to build.
SOURCES := $(TEST)_test.c ../test.c

# Objects to build.
OBJECTS := $(BLDDIR)/$(TEST)_test.o $(BLDDIR)/test.o

# Binary to build.
OUT = $(BLDDIR)/$(TEST)

# Default target.
all: $(OUT)

# Run the test.
run: $(OUT)
	./build/$(TEST)

# How to build the test binary.
$(OUT): $(OBJECTS)
	$(LD) $(LDFLAGS) -o $@ $(OBJECTS)

# How to build the test framework object.
$(BLDDIR)/test.o: ../test.c ../test.h | $(BLDDIR)
	$(CC) $(CFLAGS) -o $@ -c $<

# How to build the unit test.
$(BLDDIR)/$(TEST)_test.o: $(TEST)_test.c | $(BLDDIR)
	$(CC) $(CFLAGS) -DUNIT_TEST -o $@ -c $< -I.. -I../..

# Make sure there's an output directory.
$(BLDDIR):
	mkdir -p $(BLDDIR)

# Clean up project.
clean:
	rm -rf $(BLDDIR)
