##############################################################################
#	Custom Test Makefile
#	Zac Hester
#	2012-10-19
##############################################################################

# Run the unit test build/run procedure.
include Makefile.test
