##############################################################################
#	Generic Test Makefile
#	Zac Hester
#	2012-09-19
##############################################################################

# Run the standard unit test build/run procedure.
include ../Makefile.test
